name: Environments With Rules and Secrets Example

on:
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: dev # name of the environment in the github repo

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          echo "I am running a job in the DEV environemt."
  QA:
    runs-on: ubuntu-latest
    environment: qa # name of the environment in the github repo
    needs: DEV # name of the workflow job (NOT THE ENVIRONMENT!!)

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          echo "I am running a job in the QA environemt."
  PROD:
    runs-on: ubuntu-latest
    environment: prod # name of the environment in the github repo
    needs: QA # name of the workflow job (NOT THE ENVIRONMENT!!)

    steps:
      - uses: actions/checkout@v3

      - name: Run a script
        run: |
          echo "I am running a job in the PROD environemt."


